#!/bin/bash

xrandr --output eDP1 --mode 3200x1800
#xrandr --output DP1 --mode 2048x1280 --left-of eDP1

# DisplayLink
#xrandr --setprovideroutputsource 1 0

# Dell QHD connected to DisplayLink
#xrandr --output DVI-I-1 --mode 3840x2160 --left-of eDP1

# Dell QHD connected to USB-C
# xrandr --output DP1 --mode 3840x2160 --left-of eDP1

# Projector on USB-C dongle
#xrandr --output DP1 --mode 1920x1080 --rate 30 --left-of DVI-I-1

feh --bg-fill /usr/share/pixmaps/arch_linux-wallpaper-1366x768.jpg

# Basic layout
#i3-msg 'workspace 1; exec urxvt; workspace 10; exec urxvt; workspace 2; exec google-chrome-stable; workspace 9; exec slack'
