default_flags = "ihp"
modal = true
syntax_theme = "SolarizedDark"

[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR +{line} {file}"
leave_broot = false

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"
leave_broot = false

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
leave_broot = false
execution = "git difftool -y {file}"

[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"
leave_broot = false

[[verbs]]
key = "ctrl-d"
execution = ":page_down"

[[verbs]]
key = "ctrl-u"
execution = ":page_up"

[[verbs]]
key = "g"
execution = ":select_first"

[[verbs]]
key = "G"
execution = ":select_last"

[[verbs]]
key = "ctrl-g"
execution = ":toggle_git_status"

[[verbs]]
key = "ctrl-l"
execution = ":open_preview"

[[verbs]]
key = "ctrl-h"
execution = ":close_preview"

[skin]
default = "none none"
tree = "rgb(76,86,106) none / rgb(67,76,94) none"                     # nord3 / nord2
file = "rgb(229,233,240) none / rgb(216,222,233) none"                # nord5 / nord4
directory = "rgb(136,192,208) none bold / rgb(143,188,187) none bold" # nord8 / nord7
exe = "rgb(235,203,139) none"                                         # nord13
link = "rgb(136,192,208) none italic"                                 # nord8
pruning = "rgb(143,188,187) none italic"                              # nord7
perm__ = "rgb(76,86,106) none"                                        # nord3
perm_r = "rgb(94,129,172) none"                                       # nord10
perm_w = "rgb(129,161,193) none"                                      # nord9
perm_x = "rgb(208,135,112) none"                                      # nord12
owner = "rgb(143,188,187) none"                                       # nord7
group = "rgb(143,188,187) none"                                       # nord7
count = "rgb(180,142,173) none"                                       # nord15
dates = "rgb(163,190,140) none"                                       # nord14
sparse = "rgb(235,203,139) none"                                      # nord13
content_extract = "rgb(180,97,106) none"                              # nord11
content_match = "rgb(180,97,106) none"                                # nord11
git_branch = "rgb(180,142,173) none"                                  # nord15
git_insertions = "rgb(163,190,140) none"                              # nord14
git_deletions = "rgb(208,135,112) none"                               # nord12
git_status_current = "rgb(76,86,106) none"                            # nord3
git_status_modified = "rgb(143,188,187) none"                         # nord7
git_status_new = "rgb(235,203,139) none"                              # nord13
git_status_ignored = "rgb(67,76,94) none"                             # nord2
git_status_conflicted = "rgb(180,97,106) none"                        # nord11
git_status_other = "rgb(94,129,172) none"                             # nord10
selected_line = "none rgb(67,76,94) / none rgb(67,76,94)"             # nord2
char_match = "rgb(235,203,139) none"                                  # nord13
file_error = "rgb(180,97,106) none"                                   # nord11
flag_label = "rgb(76,86,106) none"                                    # nord3
flag_value = "rgb(163,190,140) none bold"                             # nord14
input = "rgb(236,239,244) none / rgb(236,239,244) rgb(216,222,233)"   # nord6 / nord4
status_error = "rgb(76,86,106) rgb(180,97,106)"                       # nord3 nord11
status_job = "rgb(162,190,140) rgb(76,86,106)"                        # nord14 nord3
status_normal = "rgb(59,66,82) rgb(129,161,193) / rgb(129,161,193) rgb(129,161,193)" # nord0 nord9 / nord9 nord9
status_italic = "rgb(46,52,64) rgb(129,161,193) italic / rgb(129,161,193) rgb(129,161,193)" # nord1 nord9
status_bold = "rgb(46,52,64) rgb(129,161,193) bold / rgb(129,161,193) rgb(129,161,193)" # nord0 nord9 / nord9 nord9
status_code = "rgb(59,66,82) rgb(136,192,208) / rgb(129,161,193) rgb(129,161,193)"
status_ellipsis = "gray(19) gray(1) / gray(2) gray(2)"
purpose_normal = "gray(20) gray(2)"
purpose_italic = "ansi(178) gray(2)"
purpose_bold = "ansi(178) gray(2) Bold"
purpose_ellipsis = "gray(20) gray(2)"
scrollbar_track = "gray(7) None / gray(4) None"
scrollbar_thumb = "gray(22) None / gray(14) None"
help_paragraph = "gray(20) None"
help_bold = "ansi(208) None Bold"
help_italic = "ansi(166) None"
help_code = "gray(21) gray(3)"
help_headers = "ansi(208) None"
help_table_border = "ansi(239) None"
preview = "gray(20) gray(1) / gray(18) gray(2)"
preview_line_number = "gray(12) gray(3)"
preview_match = "None ansi(29)"
hex_null = "gray(11) None"
hex_ascii_graphic = "gray(18) None"
hex_ascii_whitespace = "ansi(143) None"
hex_ascii_other = "ansi(215) None"
hex_non_ascii = "ansi(167) None"

