add_newline = false

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[!](bold yellow)"

[aws.region_aliases]
ap-southeast-2 = "au"

[directory]
style = "blue"

