[tools]
go = "latest"
python = ['3.11.4', '2.7.18']
node = "latest"
lua = "latest"
dart = "latest"
flutter = "latest"
actionlint = "latest"
ruby = "latest"
trivy = "latest"

[settings]
experimental = true
